# Generated by Django 2.1 on 2018-08-14 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TwitterClone', '0004_auto_20180814_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=280)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TwitterClone.Perfil')),
            ],
        ),
    ]
